//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerousAPI.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganisationFeeProcessing
    {
        public System.Guid Id { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<bool> IsPromoBilling { get; set; }
        public Nullable<System.DateTime> PromoBillingExpiresOn { get; set; }
    }
}
