//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerousAPI.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayConfig
    {
        public System.Guid Id { get; set; }
        public byte GatewayTypeId { get; set; }
        public string GatewayConfig { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> SystemDefault { get; set; }
        public Nullable<bool> GenerousDefaultGateway { get; set; }
    
        public virtual PaymentGatewayType PaymentGatewayType { get; set; }
    }
}
