//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerousAPI.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentProfile()
        {
            this.PaymentProfileBinInfoes = new HashSet<PaymentProfileBinInfo>();
        }
    
        public System.Guid Id { get; set; }
        public string TokenId { get; set; }
        public byte PaymentMethodId { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardExpiryMonth { get; set; }
        public string CardExpiryYear { get; set; }
        public string NameOnCard { get; set; }
        public string BankName { get; set; }
        public string BSBNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastNotifiedDateTime { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> TransactionMode { get; set; }
        public string AccountType { get; set; }
        public string CardSerurityNumber { get; set; }
    
        public virtual CardType CardType1 { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual TransactionMode TransactionMode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentProfileBinInfo> PaymentProfileBinInfoes { get; set; }
    }
}
