//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerousAPI.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentToOrganisationBatchTransactionLog
    {
        public System.Guid PaymentToOrganisationBatchLineItemId { get; set; }
        public System.Guid DonationTransactionId { get; set; }
    }
}
