//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerousAPI.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid TransactionId { get; set; }
        public byte TransactionTypeId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusUpdateDateTime { get; set; }
        public string StatusUpdateBy { get; set; }
    
        public virtual TransactionType TransactionType { get; set; }
    }
}
