//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerousAPI.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public System.Guid Id { get; set; }
        public string BankAccountTokenId { get; set; }
        public decimal Amount { get; set; }
        public string PaymentProfileTokenId { get; set; }
        public int PaymentMethodId { get; set; }
        public System.DateTime ProcessDateTime { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseText { get; set; }
    }
}
